### ISSUE TITLE
Signing in doesn't work

### ISSUE THREAD

**Issue by VelocityRa** [decaf-emu/huehuetenango#9]
Tried to sign in with GitHub and after leaving its auth page, it redirects to `https://huehuetenango.decaf-emu.com/login/callback?code=<redacted>&state=<redacted>` which shows an never-ending loading page.

**Comment by jackwakefield** [comment]
Thanks for the heads up, that's now fixed. The Docker image was missing the root certificates since moving to multi-stage builds.
